function productList() {
    const products = [
        {
            "id": 1,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Fold Over Wallet - Black",
            "description": "100% Full grain leather, 3 card pockets (Holds 1-2 cards each), 1 interior bill slot which holds multiple bills, Hand stitched for durability, Burnished and waxed edges, Ages better through time and use.",
            "price": "PHP. 1,399",
            "price_int": 1399,
            "image_1": "/img/fold_over_wallet_black_1.png",
            "image_2": "/img/fold_over_wallet_black_2.png",
            "image_3": "/img/fold_over_wallet_black_3.png",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 2,
            "category": "",
            "type": "Key Clip",
            "product_name": "Key Clip - Dark Brown",
            "description": "Snap hook mechanism. Crafted from 100% full grain leather. Fitted with a top quality antique brass key hook and key ring. Ages better through time and use.",
            "price": "PHP. 399",
            "price_int": 399,
            "image_1": "/img/key_clip_dark_brown_1.png",
            "image_2": "/img/key_clip_dark_brown_2.png",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 3,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Card Holder - Dark Brown",
            "description": "Minimalist card wallet crafted from full grain leather. 3 card pockets, fits up to 2 cards. plus some bills.",
            "price": "PHP. 799",
            "price_int": 799,
            "image_1": "/img/minimal_card_holder_dark_brown_1.jpg",
            "image_2": "/img/minimal_card_holder_dark_brown_2.jpg",
            "image_3": "/img/minimal_card_holder_dark_brown_3.jpg",
            "image_4": "/img/minimal_card_holder_dark_brown_4.jpg",
            "promo": "NO"
        },
        {
            "id": 4,
            "category": "",
            "type": "Wallet",
            "product_name": "Coin Wallet - Dark Brown",
            "description": "1 card pocket (Holds 1-3 Cards), Space inside for storing coin, cards, bills, parking slip, etc. 100% Full Grain leather with brass snap button. Ages better through time and use.",
            "price": "PHP. 1,100",
            "price_int": 1100,
            "image_1": "/img/coin_wallet_dark_brown_1.jpeg",
            "image_2": "/img/coin_wallet_dark_brown_2.jpeg",
            "image_3": "/img/coin_wallet_dark_brown_3.jpeg",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 5,
            "category": "",
            "type": "Key Chain",
            "product_name": "Swivel Key Chain - Tan",
            "description": "Crafted from premium full grain leather. Solid brass hook and key ring. Burnished and waxed edges.",
            "price": "PHP. 350",
            "price_int": 350,
            "image_1": "/img/swivel_keychain_tan_1.jpeg",
            "image_2": "/img/swivel_keychain_tan_2.jpeg",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 6,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Fold Over Wallet - Tan",
            "description": "100% Full grain leather, 3 card pockets (Holds 1-2 cards each), 1 interior bill slot which holds multiple bills, Hand stitched for durability, Burnished and waxed edges, Ages better through time and use.",
            "price": "PHP. 1,399",
            "price_int": 1399,
            "image_1": "/img/fold_over_wallet_tan.jpg",
            "image_2": "",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 7,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Fold Over Wallet - Dark -Brown",
            "description": "100% Full grain leather, 3 card pockets (Holds 1-2 cards each), 1 interior bill slot which holds multiple bills, Hand stitched for durability, Burnished and waxed edges, Ages better through time and use.",
            "price": "PHP. 1,399",
            "price_int": 1399,
            "image_1": "/img/fold_over_wallet_dark_brown.jpg",
            "image_2": "",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 8,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Card Holder - Tan",
            "description": "Minimalist card wallet crafted from full grain leather. 3 card pockets, fits up to 2 cards. plus some bills.",
            "price": "PHP. 799",
            "price_int": 799,
            "image_1": "/img/minimal_card_holder_tan_1.jpg",
            "image_2": "/img/minimal_card_holder_tan_2.jpg",
            "image_3": "/img/minimal_card_holder_tan_3.jpg",
            "image_4": "/img/minimal_card_holder_tan_4.jpg",
            "promo": "NO"
        },
        {
            "id": 9,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Card Holder - Black",
            "description": "Minimalist card wallet crafted from full grain leather. 3 card pockets, fits up to 2 cards. plus some bills.",
            "price": "PHP. 799",
            "price_int": 799,
            "image_1": "/img/minimal_card_holder_black_1.jpg",
            "image_2": "/img/minimal_card_holder_black_2.jpg",
            "image_3": "/img/minimal_card_holder_black_3.jpg",
            "image_4": "/img/minimal_card_holder_black_4.jpg",
            "promo": "NO"
        },
        {
            "id": 10,
            "category": "",
            "type": "Wallet",
            "product_name": "Coin Wallet - Black",
            "description": "1 card pocket (Holds 1-3 Cards), Space inside for storing coin, cards, bills, parking slip, etc. 100% Full Grain leather with brass snap button. Ages better through time and use.",
            "price": "PHP. 1,100",
            "price_int": 1100,
            "image_1": "/img/coin_wallet_black_1.jpeg",
            "image_2": "/img/coin_wallet_black_2.jpeg",
            "image_3": "/img/coin_wallet_black_3.jpeg",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 11,
            "category": "",
            "type": "Wallet",
            "product_name": "Coin Wallet - Tan",
            "description": "1 card pocket (Holds 1-3 Cards), Space inside for storing coin, cards, bills, parking slip, etc. 100% Full Grain leather with brass snap button. Ages better through time and use.",
            "price": "PHP. 1,100",
            "price_int": 1100,
            "image_1": "/img/coin_wallet_tan_1.jpeg",
            "image_2": "/img/coin_wallet_tan_2.jpeg",
            "image_3": "/img/coin_wallet_tan_3.jpeg",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 12,
            "category": "",
            "type": "Key Clip",
            "product_name": "Key Clip - Tan",
            "description": "Snap hook mechanism. Crafted from 100% full grain leather. Fitted with a top quality antique brass key hook and key ring. Ages better through time and use.",
            "price": "PHP. 399",
            "price_int": 399,
            "image_1": "/img/key_clip_tan_1.png",
            "image_2": "/img/key_clip_tan_2.png",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 13,
            "category": "",
            "type": "Key Chain",
            "product_name": "Swivel Key Chain - Black",
            "description": "Crafted from premium full grain leather. Solid brass hook and key ring. Burnished and waxed edges.",
            "price": "PHP. 350",
            "price_int": 350,
            "image_1": "/img/swivel_keychain_black_1.jpeg",
            "image_2": "/img/swivel_keychain_black_2.jpeg",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 14,
            "category": "",
            "type": "Key Chain",
            "product_name": "Swivel Key Chain - Dark Brown",
            "description": "Crafted from premium full grain leather. Solid brass hook and key ring. Burnished and waxed edges.",
            "price": "PHP. 350",
            "price_int": 350,
            "image_1": "/img/swivel_keychain_dark_brown_1.jpeg",
            "image_2": "/img/swivel_keychain_dark_brown_2.jpeg",
            "image_3": "",
            "image_4": "",
            "promo": "NO"
        },
        {
            "id": 15,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Card Holder v2 - Black",
            "description": "Minimalist card wallet crafted from full grain leather. 3 card pockets, fits up to 2 cards. plus some bills.",
            "price": "PHP. 950",
            "price_int": 950,
            "image_1": "/img/minimal_card_holder_black_v2_1.jpg",
            "image_2": "/img/minimal_card_holder_black_v2_2.jpg",
            "image_3": "/img/minimal_card_holder_black_v2_3.jpg",
            "image_4": "/img/minimal_card_holder_black_v2_4.jpg",
            "promo": "NO"
        },
        {
            "id": 16,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Card Holder v2 - Dark Brown",
            "description": "Minimalist card wallet crafted from full grain leather. 3 card pockets, fits up to 2 cards. plus some bills.",
            "price": "PHP. 950",
            "price_int": 950,
            "image_1": "/img/minimal_card_holder_dark_brown_v2_1.jpg",
            "image_2": "/img/minimal_card_holder_dark_brown_v2_2.jpg",
            "image_3": "/img/minimal_card_holder_dark_brown_v2_3.jpg",
            "image_4": "/img/minimal_card_holder_dark_brown_v2_4.jpg",
            "promo": "NO"
        },
        {
            "id": 17,
            "category": "",
            "type": "Wallet",
            "product_name": "Minimal Card Holder v2 - Tan",
            "description": "Minimalist card wallet crafted from full grain leather. 3 card pockets, fits up to 2 cards. plus some bills.",
            "price": "PHP. 950",
            "price_int": 950,
            "image_1": "/img/minimal_card_holder_tan_v2_1.jpg",
            "image_2": "/img/minimal_card_holder_tan_v2_2.jpg",
            "image_3": "/img/minimal_card_holder_tan_v2_3.jpg",
            "image_4": "/img/minimal_card_holder_tan_v2_4.jpg",
            "promo": "NO"
        },
    ]
    return products;
}

export { productList };